### ISSUE TITLE
I can not scan device

### ISSUE THREAD

**Issue by arno608rw** [NordicSemiconductor/IOS-nRF-Beacons#2]
I can not scan device

**Comment by philips77** [comment]
Hi, Could you please write more details? Did you follow the instructions in Help how to add a beacon?

**Comment by arno608rw** [comment]
I use nRF52-DW and use firmware nRF52_SDK_0.9.2_dbc28c9\examples\ble_peripheral\ble_app_beacon and i use ipad mini 2 
![12202479_10205228069770830_1340375141_n](https://cloud.githubusercontent.com/assets/3774145/13594280/ada8d3ba-e535-11e5-8f81-e4061f3e8492.jpg)
![12348510_10205228069890833_1040022472_n](https://cloud.githubusercontent.com/assets/3774145/13594283/adaf8afc-e535-11e5-96a2-c36c7e1f2244.jpg)
![12833469_10205228069970835_1328443460_n](https://cloud.githubusercontent.com/assets/3774145/13594281/adaaf460-e535-11e5-842b-1c9169c80afe.jpg)
![12834570_10205228070050837_1937868477_n](https://cloud.githubusercontent.com/assets/3774145/13594282/adad2294-e535-11e5-9da5-814ce8248753.jpg)

**Comment by philips77** [comment]
Hi, the iOS nRF Becaons app is scanning only for iBeacons. Since iOS version 7.something it will not scan for nRF Beacons (called here Nordic Beacons). When you buy a nRF Beacon it is configured to advertise with Nordic Semiconductor's Company ID in the Manufacturer Data. What you have to do, is switch it to Config mode and alter the Manufacturer ID to Apple's: (0x004C = 76).
You may also verify if your beacon is advertising using nRF Master Control Panel app. The Android version of this app will display it it it's advertising and show you it's data. The iOS version of nRF MCP will only display the nRF Beacon, as iBeacons are handled by CoreLocation, not CoreBluetooth, and support for them will be added in some time. The nRF Beacons app is using CoreLocation to scans for beacons so it won't see the nRF Beacon.

**Comment by po5i** [comment]
Thanks for the answer @philips77 

Didn't find it anywhere but I don't know why I didn't start to search here
